USE ROLE ACCOUNTADMIN;

-- Create dedicated Role and User
CREATE ROLE IF NOT EXISTS KAFKA_CONNECTOR_ROLE;
CREATE USER IF NOT EXISTS KAFKA_CONNECTOR_USER 
    DEFAULT_ROLE = KAFKA_CONNECTOR_ROLE;

-- Attach RSA Public Key (replace <RSA_PUBLIC_KEY_STRING> with contents of rsa_key.pub)
ALTER USER KAFKA_CONNECTOR_USER SET RSA_PUBLIC_KEY='<RSA_PUBLIC_KEY_STRING>';

-- Grant required permissions
GRANT ROLE KAFKA_CONNECTOR_ROLE TO USER KAFKA_CONNECTOR_USER;
GRANT USAGE ON WAREHOUSE CRYPTO_PULSE_WH TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT USAGE ON DATABASE CRYPTO_PULSE_DB TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT USAGE ON SCHEMA CRYPTO_PULSE_DB.PUBLIC TO ROLE KAFKA_CONNECTOR_ROLE;
-- 1. Schema-level privilege (allows creating tables)
GRANT CREATE TABLE ON SCHEMA CRYPTO_PULSE_DB.PUBLIC TO ROLE KAFKA_CONNECTOR_ROLE;

-- 2. Table-level privileges on existing tables
GRANT INSERT, SELECT ON ALL TABLES IN SCHEMA CRYPTO_PULSE_DB.PUBLIC TO ROLE KAFKA_CONNECTOR_ROLE;

-- 3. Table-level privileges on any future tables created in this schema
GRANT INSERT, SELECT ON FUTURE TABLES IN SCHEMA CRYPTO_PULSE_DB.PUBLIC TO ROLE KAFKA_CONNECTOR_ROLE;